parameters:
    base_url: '/mindsymfony4/public/'

easy_admin:
    entities:
        # List the entity class name you want to manage
        BlogPost:
            class: App\Entity\BlogPost
            list:
                actions: [ { name: 'Show' } ]
            show:
                fields:
                - id
                - title
                - published
                - { property: 'comments', template: 'comments.html.twig' }
                - images
        Comment:
            class: App\Entity\Comment
        Image:
            class: App\Entity\Image
            list:
                fields:
                - id
                - { property: 'url', type: 'image', label: 'Image', 'base_path': "%base_url%" }
            form:
                fields:
                - { property: 'file', type: 'vich_image', label: 'Image' }
        User:
            class: App\Entity\User
            controller: App\Controller\Admin\UserController

    design:
        menu:
            - { entity: 'BlogPost', icon: 'newspaper' }
            - { entity: 'Comment', icon: 'comments' }
            - { entity: 'Image', icon: 'images' }
            - { entity: 'User', icon: 'users' }
            - { label: 'Front End', route: 'default_index', icon: 'home' }
