monolog:
    handlers:
        token_confirmation:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.token_confirmation.log"
            channels: [token_confirmation]
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug # debug|info|notice|warning|error|critical|alert|emergency
            channels: ["!event", "!token_confirmation", "!php"]
        deprecation:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.deprecations.log"
        deprecation_filter:
            type: filter
            handler: deprecation
            max_level: info
            channels: ["php"]
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
